name: "First Workflow"

on: workflow_dispatch

jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: "Print Greeting"
        run: echo "Hello, World!"
      - name: "Print Greeting"
        run: cat /etc/*release
